//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyMonitorApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBodyValues
    {
        public int Id { get; set; }
        public int BodyId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public decimal Weight { get; set; }
        public decimal Neck { get; set; }
        public decimal Chest { get; set; }
        public decimal Biceps { get; set; }
        public decimal Stomach { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
